#!/usr/bin/env python
#_*_coding:utf-8_*_

import os
os.system("ls -la")
print os.environ

array,target = [2,3,4],6
print array
print target
for i in array:
    for j in array:
        if i + j == target:
            print i , j
            i_ = array.index(i)
            j_ = array.index(j)
            if i_ != j_:
                print 'i  >>   ', array.index(i)+1, '  j   >>  ', array.index(j)+1
